name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build and test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - name: "Build @do-it-plz/core"
        working-directory: packages/core
        run: bun run build
      - name: "Build @do-it-plz/client"
        working-directory: packages/client
        run: bun run build
      - name: "Build @do-it-plz/next"
        working-directory: packages/next
        run: bun run build
      - run: bun test
